version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodocker
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data/:/data/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  web:
    build: .
    #command: python manage.py runserver 0:8000
    ports:
      - "80:8000"
    command:
      - sh
      - -c 
      - |
         python /code/manage.py migrate
         uwsgi --ini uwsgi.ini
    working_dir: /code/web
    volumes:
      - .:/code
    #ports:
    #  - "7777:7777"
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 512M


  celery_user:
    build: .
    command: celery -A qinglianjie worker -Q user
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  celery_back:
    build: .
    command: celery -A qinglianjie worker -B -Q back
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M