# Generated by Django 3.2.4 on 2021-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210619_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
