# Generated by Django 3.2.4 on 2021-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_courseinfo_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorequeryresult',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
