# Generated by Django 3.2.4 on 2021-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_scorequeryresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablequeryresult',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
