# Generated by Django 3.2.4 on 2021-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_timetablequeryresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorequeryresult',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pending', 'Pending'), ('Success', 'Success'), ('Never', 'Never')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetablequeryresult',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pending', 'Pending'), ('Success', 'Success'), ('Never', 'Never')], default='Pending', max_length=10),
        ),
    ]
