# Generated by Django 3.2.4 on 2021-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_noticetask_qqbindinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticetask',
            name='qq_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qqbindinfo',
            name='qq_id',
            field=models.IntegerField(default=0),
        ),
    ]
