# Generated by Django 3.2.4 on 2021-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210626_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuaccountinfo',
            name='qq_me_when_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticetask',
            name='qq_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qqbindinfo',
            name='qq_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
