# Generated by Django 3.2.4 on 2021-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210627_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetask',
            name='type',
            field=models.CharField(choices=[('QQ', 'QQ'), ('Group', 'Group')], default='QQ', max_length=10),
        ),
    ]
