# Generated by Django 3.2.4 on 2021-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_noticetask_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(default=0)),
                ('notice_when_xk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XKInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='qqbindinfo',
            name='notice_when_xk',
            field=models.BooleanField(default=False),
        ),
    ]
