# Generated by Django 3.2.4 on 2021-07-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210718_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatisticsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
            ],
        ),
    ]
