# Generated by Django 3.2.4 on 2021-07-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_lastrefreshtimeofspecialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='score',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
