# Generated by Django 3.2.4 on 2021-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuaccountinfo',
            name='pingan_daily',
            field=models.BooleanField(default=False),
        ),
    ]
