# Generated by Django 3.2.4 on 2021-09-12 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_heuaccountinfo_pingan_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatisticsresult',
            name='is_fubaijie_data',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FubaijieCourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('anonymous', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
                ('score', models.CharField(blank=True, default='', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
